output "node_groups" {
  description = "Outputs from EKS node groups. Map of maps, keyed by var.node_groups keys"
  value = {
    for k, v in aws_eks_node_group.workers : k => {
      # values set/generated by terraform-aws-eks
      iam_role_arn = v.node_role_arn
      name         = v.node_group_name
      # output from AWS
      arn       = v.arn
      id        = v.id
      status    = v.status
      resources = v.resources
    }
  }
}

output "aws_auth_roles" {
  description = "Roles for use in aws_auth ConfigMap"
  value = [
    for k, v in local.node_groups_expanded : {
      worker_role_arn = lookup(v, "iam_role_arn", var.default_iam_role_arn)
      platform        = "linux"
    }
  ]
}
