output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "sqs_queue_asg_notification_arn" {
  description = "SQS queue ASG notification ARN"
  value       = module.aws_node_termination_handler_sqs.sqs_queue_arn
}

output "sqs_queue_asg_notification_url" {
  description = "SQS queue ASG notification URL"
  value       = module.aws_node_termination_handler_sqs.sqs_queue_id
}
