name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install zensical
        run: pip install zensical

      - name: Build docs
        run: zensical build --clean

      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - uses: actions/deploy-pages@v4
        id: deployment
